/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.jonathanparra1013.astrocade.AstroCadeVisual;

/**
 *
 * @author jonap
 */
import com.github.jonathanparra1013.astrocade.PremioPorMaquina;
import com.github.jonathanparra1013.astrocade.Administrador;
import com.github.jonathanparra1013.astrocade.Cliente;
import com.github.jonathanparra1013.astrocade.Tarjeta;
import com.github.jonathanparra1013.astrocade.Diamond;
import com.github.jonathanparra1013.astrocade.MaquinaRuleta;
import com.github.jonathanparra1013.astrocade.MaquinaCarreras;
import com.github.jonathanparra1013.astrocade.MaquinaDisparos;
import com.github.jonathanparra1013.astrocade.MaquinaGarra;
import com.github.jonathanparra1013.astrocade.PremioPorMaquina;

import javax.swing.*;
import java.awt.*;
import java.util.Date;
public class IngresarVista extends javax.swing.JFrame {
    
    private Administrador admin;
    private Cliente cliente;
    private Tarjeta tarjeta;
    private MaquinaRuleta ruleta;
    private MaquinaCarreras carreras;
    private MaquinaDisparos disparos;
    private MaquinaGarra garra;

    public IngresarVista() {
        initComponents();
        inicializarDatosLogica();
        setLocationRelativeTo(null); 
    }

    private void inicializarDatosLogica() {
        // Datos de prueba iniciales
        admin = new Administrador("ADM-01", "Administrador Principal", "admin@astrocade.com", "1234");
        cliente = new Cliente("CLI-01", "Jonathan Parra", "jonathan@email.com", new Date());
        tarjeta = new Diamond("TARJ-001");
        tarjeta.recargarSaldo(100000); 

        // Máquinas y premios
        PremioPorMaquina[] premiosGarra = { new PremioPorMaquina("Oso de Peluche", 5) };
        PremioPorMaquina[] premiosRuleta = { new PremioPorMaquina("Consola Mini", 2) };

        ruleta = new MaquinaRuleta("Ruleta de la Fortuna", 5000, premiosRuleta);
        carreras = new MaquinaCarreras("Speed Racer", 3000);
        disparos = new MaquinaDisparos("Target Shooter", 4000);
        garra = new MaquinaGarra("Garra Mágica", 2500, premiosGarra);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrador", "Cliente" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel1.setText("Seleccione Tipo de Usuario");

        jLabel2.setText("BIENVENIDO A ASTROCADE");

        jLabel3.setText("(Simulacion Arcade)");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Salir");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(118, 118, 118))))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButton1)
                .addGap(72, 72, 72)
                .addComponent(jButton2)
                .addGap(0, 105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rol = (String) jComboBox1.getSelectedItem();

        if ("Administrador".equals(rol)) {
            String pass = JOptionPane.showInputDialog(this, "Ingrese la contraseña de Administrador:", "Autenticación", JOptionPane.QUESTION_MESSAGE);
            if (pass != null && admin.validarPassword(pass)) {
                JOptionPane.showMessageDialog(this, "¡Acceso Concedido!");
                new AdminVista(admin, cliente, tarjeta, ruleta, carreras, disparos, garra).setVisible(true);
                this.dispose();
            } else if (pass != null) {
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if ("Cliente".equals(rol)) {
            new ClienteVista(cliente, tarjeta, ruleta, carreras, disparos, garra).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un tipo de usuario válido.", "Atención", JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IngresarVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
